spring:
  application:
    name: demo02-mp-wrapper
  profiles:
    active: mysql
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  type-aliases-package: com.study.pojo
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      table-prefix: t_    # 表名前缀，不用在每个实体类上配置@Table_name了
      id-type: assign_id    # 全局将主键设置为雪花算法策略
server:
  port: 8080
  servlet:
    context-path: /
